services:
  #PostgreSQL container
  db:
    container_name: 3dp_db
    image: postgres:15
    environment:
      POSTGRES_USER: threedp_user
      POSTGRES_PASSWORD: 3dpplatform
      POSTGRES_DB: threedp_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    #FastAPI container
  api:
    build:
      context: ./backend
    container_name: 3dp_api
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://threedp_user:3dpplatform@db:5432/threedp_db
      SECRET_KEY: oVOyHvJuPbUTopgqBfrKdAnHGkSo87P6cjviDkX96gYg8xbtYLqPVbySx9zPPM13
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
      REFRESH_TOKEN_EXPIRE_DAYS: 7
      ADMIN_SIGNUP_KEY: 3dp-admin-2026
    depends_on:
      - db
    volumes:
      - ./backend:/app

volumes:
  postgres_data:
