// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu8QaACcPEzC1MeypqVM5hBkz0MLL962w',
    appId: '1:514800575116:web:0d01462702e2a3e06211a9',
    messagingSenderId: '514800575116',
    projectId: 'dp-platform-3856f',
    authDomain: 'dp-platform-3856f.firebaseapp.com',
    storageBucket: 'dp-platform-3856f.firebasestorage.app',
    measurementId: 'G-PC581QMFSY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBctIN_ptMCb1HFEVEO19LoL6LAILwjVDk',
    appId: '1:514800575116:android:9df0c82552c584d76211a9',
    messagingSenderId: '514800575116',
    projectId: 'dp-platform-3856f',
    storageBucket: 'dp-platform-3856f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwifImCqbbWmlzIT2uT6pCR-FlI-F26vY',
    appId: '1:514800575116:ios:8b5caacde919c9226211a9',
    messagingSenderId: '514800575116',
    projectId: 'dp-platform-3856f',
    storageBucket: 'dp-platform-3856f.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );
}
