import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'app.dart';
import 'core/router/app_router.dart';
import 'core/router/app_routes.dart';
import 'features/notifications/fcm/fcm_service.dart';
// Generated by `flutterfire configure`. If this import fails to resolve,
// run the CLI command first — see docs/notifications_fcm_setup.md §4.
import 'firebase_options.dart';

/// Captured before GoRouter initialises so the splash screen can restore
/// the intended URL even when auth redirects would otherwise overwrite it.
String initialWebRoute = '/';

/// Deep-link route resolved from a push tap that launched the app from a
/// terminated state. Splash consumes this AFTER auth resolves so the
/// regular landing logic doesn't overwrite it. Empty when no pending tap.
String pendingPushRoute = '';

/// Resolve a push `data` payload to an in-app route. Mirrors the logic
/// inside `NotificationHistoryScreen._deepLinkFor`.
String? routeFromPushData(Map<String, dynamic> data) {
  final jobId = data['job_id']?.toString();
  if (jobId != null && jobId.isNotEmpty) return '/jobs/$jobId';
  final printerId = data['printer_id']?.toString();
  if (printerId != null && printerId.isNotEmpty) return '/printers/$printerId';
  final stlId = data['stl_id']?.toString();
  if (stlId != null && stlId.isNotEmpty) return '/upload/file/$stlId';
  return null;
}

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  if (kIsWeb) {
    final uri = Uri.base;
    initialWebRoute = uri.hasQuery ? '${uri.path}?${uri.query}' : uri.path;
  }

  await dotenv.load(fileName: '.env');

  // Firebase + FCM. Wrapped in a try so the app still boots if the native
  // platform config hasn't been added yet (web fallback / dev machine).
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
    // Listener handles WARM taps (app in background → opened by tap).
    FcmService.instance.tapEvents.listen(_handleNotificationTap);
    await FcmService.instance.start();

    // Cold-start tap (terminated → tapped): convert to a route string
    // and let SplashScreen take it from `pendingPushRoute` after auth.
    final initial = FcmService.instance.consumePendingInitial();
    if (initial != null) {
      final route = routeFromPushData(initial);
      if (route != null) {
        pendingPushRoute = route;
        if (kDebugMode) {
          // ignore: avoid_print
          print('[fcm] cold-start deep link → $route');
        }
      }
    }
  } catch (e) {
    if (kDebugMode) {
      // ignore: avoid_print
      print('[fcm] startup skipped: $e');
    }
  }

  runApp(const ProviderScope(child: App()));
}

/// Warm-state tap handler (app already running). Cold-start taps are
/// handled via `pendingPushRoute` + splash.
void _handleNotificationTap(Map<String, dynamic> data) {
  final route = routeFromPushData(data);
  appRouter.push(route ?? AppRoutes.notifications);
}
